name: Spring Boot CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Start Spring Boot application
        run: ./gradlew bootRun &
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Wait for application to start
        run: sleep 10

      - name: Health Check
        run: curl --fail http://localhost:8080/health_check